### ISSUE TITLE
国家地理people变成life time了

### ISSUE THREAD

**Issue by gfwfuckoff** [hououinkami/AppleTV#2]
EXTINF:-1 tvg-id="283" tvg-logo="http://tv.sason.xyz/logo/ng.png" group-title="H 科教记录",国家地理 悠人 ★ 

-http://125.227.198.89:8030

life time没有失效，请问可以加入吗？

**Comment by hououinkami** [comment]
我下午更新了列表，刚看了下people没有问题诶，life time你指的是哪一个呢？
如果有其他个别台相加可以直接把地址发给我，如果觉得还不错我我就加进去吧，我用的主要是sason大神提供的源，出于强迫症才自己搞了个自用版的😂

**Comment by gfwfuckoff** [comment]
我刚刚看的时候 科教记录没有在hktw分类了，能请弄个聚合的m3u吗，tivimate太多节目单了，每个节目单分类中的台并不多，操作起来挺麻烦的

**Comment by hououinkami** [comment]
> 我刚刚看的时候 科教记录没有在hktw分类了，能请弄个聚合的m3u吗，tivimate太多节目单了，每个节目单分类中的台并不多，操作起来挺麻烦的

你说的分类指的是之前分成几个m3u还是说group字段分太多？因为我没用tivimate所以对它的操作不太清楚
我换了个AppleTV上的App，现在搞了一个聚合了的了，根目录下IPTV.m3u，然后把图标都换成透明背景的了。今天有空的话应该还会在稍微改一改，不过现在group字段现在还是维持原有那几个

**Comment by gfwfuckoff** [comment]
@hououinkami 对的，我之前只用hktw分类，毕竟用iptv目的肯定不是为了看ccav的😁，最近hktw频道慢慢变少了，后来用了iptv分类，希望这个分类能把电影分类加上，谢谢

**Comment by gfwfuckoff** [comment]
lifetime是指，之前有字幕的国际地理悠人频道，它那几天变成了lifetime了
，现在这个链接已经失效了

**Comment by hououinkami** [comment]
> @hououinkami 对的，我之前只用hktw分类，毕竟用iptv目的肯定不是为了看ccav的😁，最近hktw频道慢慢变少了，后来用了iptv分类，希望这个分类能把电影分类加上，谢谢

之前的电影分类几个台的来源一个月没更新了，失效得只剩一个台，所以就没拉取那个数据把电影分类取消了，目前港台源只留了sason的加上翡翠和明珠，无线新闻一直想要但找不到稳定源😂

**Comment by gejh2014** [comment]
国家地理 有M3u 直播源吗？
